language: csharp
sudo: false
dotnet: 2.1.2
dist: trusty
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
mono: none
services:
  - mongodb
os:
  - linux
#  - osx
osx_image: xcode8.1
addons:
  apt:
    packages:
      - libunwind8
branches:
  only:
    - master
    - release
    - develop
    - /^rel\/.*/
    - /^(.*\/)?ci-.*$/
script:
  - ./build.sh