init:
  - git config --global core.autocrlf true
build_script:
  - ps: .\run.ps1 default-build
clone_depth: 1
test: off
services:
  - mongodb
branches:
  only:
    - release
    - develop
    - master
    - /^(.*\/)?ci-.*$/
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
matrix:
  fast_finish: true
artifacts:
  - path: 'artifacts\build\*.nupkg'
    name: MyGet
deploy:
  - provider: Environment
    name: MyGet
    artifact: 'artifacts\build\*.nupkg'
    on:
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
image:
- Visual Studio 2017
