only_commits:
  # Start a build if commit message contains 'appveyor'
  message: /appveyor/
init:
  - git config --global core.autocrlf true
build_script:
  - ps: .\build.ps1
clone_depth: 1
test: off
deploy: off
# See http://www.appveyor.com/docs/services-databases
services:
  - mongodb
branches:
  only:
    - release
    - develop
    - master
    - /^(.*\/)?ci-.*$/
environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
matrix:
  fast_finish: true
artifacts:
  - path: 'artifacts\build\*.nupkg'
os: Visual Studio 2017
