version: '3.4'

services:
  mongo-efcore:
    image: mongo:4.1.2-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "mongodb-efcore-data:/data/db"
  mongo-efcore-express:
    image: mongo-express
    restart: always
    ports:
      - 27027:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo-efcore
volumes:
  mongodb-efcore-data:
    external: true